### ISSUE TITLE
hotfix:高危语句规则页面增加搜索等通用操作

### ISSUE THREAD

**Issue by XiaoE0203** [TencentBlueKing/bk-job#1345]
![image](https://user-images.githubusercontent.com/54015094/191266544-95dc82a1-7090-401b-8e37-65861102891f.png)

**Comment by nekzhang** [comment]
1. 增加搜索框
  - 语法检测表达式
    纯字符串模糊搜索
  - 规则说明
    纯字符串模糊搜索
  - 脚本类型
    枚举选择、可多选
  - 动作
    枚举选择、可多选
2. 支持排序
  - 字符串类型的字段，按字母正/倒序切换
  - 枚举类型的、先分类再排序
4. 增加展示字段可配置
  - 创建人
  - 创建时间
  - 最近更新人
  - 最近更新时间

**Comment by nekzhang** [comment]
高危语句的检测规则会严格按照列表的顺序进行优先级的先后匹配，所以这里只提供用户可以搜索即可，不需要排序了。
