### ISSUE TITLE
bugfix: 作业执行详情-根据日志内容检索，如果关键字包含特殊字符会报错

### ISSUE THREAD

**Issue by wangyu096** [TencentBlueKing/bk-job#1441]
**Version / Branch / tag**

3.7.0-beta.23

**出了什么问题？(What Happened?)**
作业执行详情-根据日志内容检索，如果关键字包含特殊字符会报错
![image](https://user-images.githubusercontent.com/28581184/199195185-252daae0-fc0e-4cd4-821d-57fd6fd6b7b7.png)

**如何复现？(How to reproduce?)**

检索关键字包含“=”等特殊字符

**预期结果(What you expect?)**

不报错

**Comment by wangyu096** [comment]
<img width="1639" alt="image" src="https://user-images.githubusercontent.com/28581184/199195369-27ed0f87-c548-466e-bf27-a131c33c6064.png">

spring cloud feign 框架bug。详情见

https://github.com/spring-cloud/spring-cloud-openfeign/issues/448

**Comment by fabio-he** [comment]
![image](https://user-images.githubusercontent.com/56472792/218385942-06d6deb2-7113-4427-8b68-c1f16c46b97c.png)

**Comment by fabio-he** [comment]
![image](https://user-images.githubusercontent.com/56472792/218386235-6d96b7bb-149a-4c75-b7df-db399ff6c0aa.png)
