### ISSUE TITLE
feature: Job 3.7.x 版本运维部署支持新增的变量

### ISSUE THREAD

**Issue by wangyu096** [TencentBlueKing/bk-job#1743]
1. 【新增】BK_API_GATEWAY_GSE_URL
蓝鲸 GSE API Gateway url。格式:{网关访问地址}/{网关环境}，网关访问地址、网关环境的取值见bk-gse网关API文档
2. 【新增】Job 公共MQ 配置BK_JOB_RABBITMQ_HOST/BK_JOB_RABBITMQ_PORT/BK_JOB_RABBITMQ_USERNAME/BK_JOB_RABBITMQ_PASSWORD/BK_JOB_RABBITMQ_VHOST
3. 【删除】BK_JOB_MANAGE_RABBITMQ_* 相关的配置。BK_JOB_MANAGE_RABBITMQ_HOST/BK_JOB_MANAGE_RABBITMQ_PORT/BK_JOB_MANAGE_RABBITMQ_USERNAME/BK_JOB_MANAGE_RABBITMQ_PASSWORD/BK_JOB_MANAGE_RABBITMQ_VHOST

**Comment by synonez** [comment]
6.2版本部署脚本已实现

**Comment by wangyu096** [comment]
done
