### ISSUE TITLE
bugfix: 执行sql脚本模板不严谨

### ISSUE THREAD

**Issue by liuliaozhong** [TencentBlueKing/bk-job#1755]
**出了什么问题？(What Happened?)**
执行sql脚本，当服务器上有两个mysql实例，分别启动映射两个端口，例如3306和33060的情况时，模板脚本会grep到两个端口，会报错
![image](https://user-images.githubusercontent.com/120009833/220340556-db827d7c-70cc-48af-8f4f-557f70020301.png)

![image](https://user-images.githubusercontent.com/120009833/220311166-be48a699-4f53-47ca-be52-d9a885406d5a.png)

**Comment by wangyu096** [comment]
done
