### ISSUE TITLE
bugfix: 创建定时任务时使用执行方案中的默认密文变量不生效

### ISSUE THREAD

**Issue by jsonwan** [TencentBlueKing/bk-job#1764]
**Version / Branch / tag**
3.5.x

**出了什么问题？(What Happened?)**
创建定时任务时使用执行方案中的默认密文变量不生效

**如何复现？(How to reproduce?)**
创建含有密文变量的模板及执行方案，步骤中用脚本echo出对应的密文变量，使用该执行方案创建定时任务，创建时不指定任何变量直接保存，开启定时任务执行后发现脚本中输出的不是执行方案的密文变量值。

**预期结果(What you expect?)**
定时任务执行后脚本中输出执行方案中的密文变量值。

**Comment by fabio-he** [comment]
在新增定时任务绑定执行方案时,不修改密文变量会打印初始值,修改密文变量,原先显示*的会以*密文形式显示
