### ISSUE TITLE
bugfix: 脚本引用密文变量不生效

### ISSUE THREAD

**Issue by wangyu096** [TencentBlueKing/bk-job#1853]
**Version / Branch / tag**

3.6.x -3.7.x

**出了什么问题？(What Happened?)**
脚本引用密文变量不生效
<img width="524" alt="image" src="https://user-images.githubusercontent.com/28581184/226236361-4dd6b4d1-4368-4d08-b474-e6c8b5948039.png">
<img width="913" alt="image" src="https://user-images.githubusercontent.com/28581184/226236446-ae6c7ffe-f2cc-4914-ae9c-c25e7ee4add0.png">
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/28581184/226236501-f15cc7c3-a4d8-440b-ba86-47512ddc127b.png">

**如何复现？(How to reproduce?)**

密文变量必现

**预期结果(What you expect?)**

**Comment by fabio-he** [comment]
![image](https://user-images.githubusercontent.com/56472792/228774468-a2d69fee-9524-41a8-81dd-ce36b3c90bc9.png)
tested
