### ISSUE TITLE
bugfix: 执行详情页面关键字检索未匹配任何Agent执行日志，但是过滤出来的主机列表不为空

### ISSUE THREAD

**Issue by wangyu096** [TencentBlueKing/bk-job#1874]
**Version / Branch / tag**

3.6.2-rc.4

**出了什么问题？(What Happened?)**
执行详情页面关键字检索功能，如果没有任何关键字匹配，那么过滤出来的主机列表是全量的（预期应该是空的列表）

<img width="1691" alt="image" src="https://user-images.githubusercontent.com/28581184/227481474-587635b8-6df5-4fc7-b260-b1f9c42266b3.png">

**如何复现？(How to reproduce?)**

3.6.2-rc.4 版本必现，3.7版本无此问题

**预期结果(What you expect?)**

**Comment by fabio-he** [comment]
![image](https://user-images.githubusercontent.com/56472792/228750574-df0aa505-d5c4-4710-bc61-01085e44c6e9.png)
tested

**Comment by fabio-he** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
