### ISSUE TITLE
bugfix: 快速分发文件源和目标服务器相同提示框,点击窗口×号效果与"是的,确定无误"一样

### ISSUE THREAD

**Issue by hLinx** [TencentBlueKing/bk-job#1877]
**Version / Branch / tag**

3.6.x
**出了什么问题？(What Happened?)**
<img width="784" alt="image" src="https://user-images.githubusercontent.com/17508060/227836079-7c44aeda-f06d-4a10-9cbd-00123b2d65a8.png">

**如何复现？(How to reproduce?)**

**预期结果(What you expect?)**

**Comment by fabio-he** [comment]
tested 移除了 ×号
