### ISSUE TITLE
fix: cron 中文翻译错误

### ISSUE THREAD

**Issue by hLinx** [TencentBlueKing/bk-job#2217]
**Version / Branch / tag**

3.6.x,3.7.x
**出了什么问题？(What Happened?)**

![Uploading 企业微信截图_4ca2cda9-c396-4252-83a2-2cd267a9f1d8.png…]()

**如何复现？(How to reproduce?)**

**预期结果(What you expect?)**

**Comment by fabio-he** [comment]
![image](https://github.com/TencentBlueKing/bk-job/assets/56472792/6247bd9c-335d-48fc-ad85-2b730478d936)
每天 从凌晨0点 *(10点)开始每隔5个小时 从00分 *(50分)  开始每隔5分钟

**Comment by fabio-he** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
