### ISSUE TITLE
fix: 脚本检查报错 do not redirect data to block devices

### ISSUE THREAD

**Issue by wangyu096** [TencentBlueKing/bk-job#2275]
**Version / Branch / tag**

3.4.x-3.7.x

**出了什么问题？(What Happened?)**
脚本检查报错 do not redirect data to block devices。脚本内容
```
#!/bin/bash
tee -a /tmp/ddm.log
```
<img width="940" alt="image" src="https://github.com/TencentBlueKing/bk-job/assets/28581184/f9ed3507-761e-49ba-a41e-15e9b09595e1">

**如何复现？(How to reproduce?)**
见问题描述

**预期结果(What you expect?)**
正常脚本，无需报错

**Comment by wangyu096** [comment]
### 问题定位
DeviceCrashScriptChecker.java
<img width="1118" alt="image" src="https://github.com/TencentBlueKing/bk-job/assets/28581184/aa8d9e3b-3062-4e22-9466-0a7f88c60f52">
正则表达式写法不太合理

**Comment by liuliaozhong** [comment]
已讨论商量了，是提示级别的报错，可以保留
