### ISSUE TITLE
【高危语句规则】新增高危语句规则管理功能的API，给上层SaaS使用

### ISSUE THREAD

**Issue by pagezz-canway** [TencentBlueKing/bk-job#2383]
原始需求：
客户希望可以管理高危命令，并且部分用户已有建成内部的高危命令管理模块/工具，希望可以对接。
在使用的过程中，希望脚本、作业等的执行前，如果碰到某些高等级高危命令如rm -rf可以触发审核机制，普通级别高危命令可以忽略。

接口需求：
1、提供高危语句规则的增删改查接口，方便客户从第三方系统同步检测语句
2、提供脚本的高危命令检测接口
输入：脚本ID
输出：检测结果
1）总结果（有一条不通过即失败）
2）每个高危语句对应的具体结果

**Comment by nekzhang** [comment]
1. 提供高危语句规则的增删改查接口，方便客户从第三方系统同步检测语句
----------------------------
这个需求可以支持


2. 提供脚本的高危命令检测接口
----------------------------
这个无法支持！因为高危命令检测并不是JOB提供的平台能力之一，它仅仅是JOB为自身的脚本执行能力提供的辅助检测功能，且也仅对JOB执行的脚本动作有效。
