### ISSUE TITLE
fix: 执行方案传入的目标主机为空时，报错信息不明确

### ISSUE THREAD

**Issue by wangyu096** [TencentBlueKing/bk-job#2389]
**Version / Branch / tag**
 3.7.x

**出了什么问题？(What Happened?)**
3.7.x 执行方案传入的目标主机为空时，报错信息为 500 内部错误，而不是明确提示用户目标主机不存在。

**Comment by wangyu096** [comment]
## 定位
<img width="1624" alt="image" src="https://github.com/TencentBlueKing/bk-job/assets/28581184/3783ee96-0ae4-4f5a-8047-b70374e2a5bb">
<img width="1630" alt="image" src="https://github.com/TencentBlueKing/bk-job/assets/28581184/9f3b79af-831d-488b-9dd4-14104a9802aa">
<img width="1173" alt="image" src="https://github.com/TencentBlueKing/bk-job/assets/28581184/8e5e48b5-608d-49b3-8cdc-7503481fdd9b">

**Comment by fabio-he** [comment]
![image](https://github.com/TencentBlueKing/bk-job/assets/56472792/27fd5168-cc5a-482a-a6cc-cd35c395dc82)

**Comment by fabio-he** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
