### ISSUE TITLE
fix: 执行详情任务名称超长页面错乱

### ISSUE THREAD

**Issue by hLinx** [TencentBlueKing/bk-job#2545]
**Version / Branch / tag**

**出了什么问题？(What Happened?)**

**如何复现？(How to reproduce?)**

**预期结果(What you expect?)**

**Comment by fabio-he** [comment]
![image](https://github.com/TencentBlueKing/bk-job/assets/56472792/5bee949c-474c-41e3-bc1a-a543a44a8619)
![image](https://github.com/TencentBlueKing/bk-job/assets/56472792/7814b726-fb91-45cb-84ff-c654a10afec4)

**Comment by fabio-he** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
