### ISSUE TITLE
fix: 脚本版本管理的“被引用”数据有错

### ISSUE THREAD

**Issue by nekzhang** [TencentBlueKing/bk-job#2595]
**Version / Branch / tag**
V3.8.X

**出了什么问题？(What Happened?)**
<img width="1187" alt="image" src="https://github.com/TencentBlueKing/bk-job/assets/3852595/f017d568-d290-45bb-8201-081a118adab8">
<img width="1382" alt="image" src="https://github.com/TencentBlueKing/bk-job/assets/3852595/19e76701-2ec1-427f-8d14-c6f7947c1d25">

脚本版本管理里的 `被引用` 数据是错的

**如何复现？(How to reproduce?)**

**预期结果(What you expect?)**
`被引用` 的数据要对得上

**Comment by wangyu096** [comment]
缺陷原因：引用计算包含了内置隐藏的用于调试的执行方案，需要过滤掉
