### ISSUE TITLE
fix: 执行超时时间为空时前端传值应该是 null

### ISSUE THREAD

**Issue by hLinx** [TencentBlueKing/bk-job#2763]
**Version / Branch / tag**
3.8.x

**出了什么问题？(What Happened?)**

**如何复现？(How to reproduce?)**

**预期结果(What you expect?)**

**Comment by fabio-he** [comment]
![image](https://github.com/TencentBlueKing/bk-job/assets/56472792/18a71b9c-125c-4b5d-b8fe-a0fea1018192)

**Comment by fabio-he** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
