### ISSUE TITLE
想问一下，部署依赖相关的事项

### ISSUE THREAD

**Issue by Zzzz1111** [TencentBlueKing/bk-job#2819]
你好，想问一下，bk-job可以单独部署么？文档中提到的蓝鲸基础环境是指蓝鲸社区版环境么？如果不是的话，是指的哪些？bk-job需要的最少依赖的组件有哪些？

**Comment by jsonwan** [comment]
bk-job可以单独部署么？
不可以单独部署。

文档中提到的蓝鲸基础环境是指蓝鲸社区版环境么？如果不是的话，是指的哪些？
是的，蓝鲸社区版环境。

bk-job需要的最少依赖的组件有哪些？
CMDB，IAM，APIGW/ESB，GSE，BKREPO（分发本地文件需要），PAAS（发送消息通知需要）

**Comment by Zzzz1111** [comment]
好的 十分感谢
