### ISSUE TITLE
添加服务器页面，输入IPv4或IPv6无法进行模糊匹配

### ISSUE THREAD

**Issue by liuliaozhong** [TencentBlueKing/bk-job#2875]
version： 3.7+
在添加服务器页面即使我选择IPv4(或者IPv6)地址，输入过程没有动态过滤，也不支持模糊搜索，没有输完整情况下回车无效：
![image](https://github.com/TencentBlueKing/bk-job/assets/120009833/c483f2ad-e02f-4ba0-b993-a48765925f58)
期望可以动态模糊匹配

**Comment by nekzhang** [comment]
OK，可以支持

**Comment by nekzhang** [comment]
已上线！
