### ISSUE TITLE
fix: 轻量化部署模式下分发配置文件失败

### ISSUE THREAD

**Issue by jsonwan** [TencentBlueKing/bk-job#2933]
**Version / Branch / tag**
3.8.x

**出了什么问题？(What Happened?)**
轻量化部署模式下分发配置文件失败，报错如下：
![image](https://github.com/TencentBlueKing/bk-job/assets/53823124/5d16dcd4-a353-448f-99b5-42116da44a8c)

**如何复现？(How to reproduce?)**
通过节点管理更新插件配置，触发轻量化部署模式下分发配置文件

**预期结果(What you expect?)**
轻量化部署模式下分发配置文件成功

**Comment by jsonwan** [comment]
原因：轻量化部署模式下缺少将容器内路径映射到母机上路径的配置

**Comment by wangyu096** [comment]
done
