### ISSUE TITLE
fix: 普通用户没有删除公共脚本管理权限，去申请跳转至404页面

### ISSUE THREAD

**Issue by liuliaozhong** [TencentBlueKing/bk-job#2939]
**Version / Branch / tag**
3.8.x

**出了什么问题？(What Happened?)**
普通用户没有删除公共脚本管理权限，去申请
![image](https://github.com/TencentBlueKing/bk-job/assets/120009833/340ae947-2d15-48b0-a976-6f110dc1ae6f)
跳转到申请权限页面404
![image](https://github.com/TencentBlueKing/bk-job/assets/120009833/5f7a0e71-c261-496a-8805-a984a0f9a0b8)

**如何复现？(How to reproduce?)**

**预期结果(What you expect?)**

**Comment by wangyu096** [comment]
done
