### ISSUE TITLE
feat: AI+JOB 一期

### ISSUE THREAD

**Issue by nekzhang** [TencentBlueKing/bk-job#2995]
### 需求背景
随着AI智能化辅助场景越来越丰富，显著的帮助用户提升效率；在指令执行场景中，同样有迫切需要更贴近场景化的AI辅助能力！如，编写脚本时碰到的问题、处理脚本报错等等，多少都会需要借搜索引擎来帮助自己解决问题；但搜索引擎提供的更多的是碎片化的信息、关联性的查询结果，迫切需要通过AI的能力快速为用户提供解决方案！

### 需求描述
- AI辅助场景
  - 脚本纠错 `1期`
  <img width="1464" alt="image" src="https://github.com/TencentBlueKing/bk-job/assets/3852595/c2bea9b2-8f55-42fb-aad7-e83a9b1fd0ba">

  - 脚本指导 `1期`
  提供AI自然语言对话框（类ChatGPT），用户按需对话提问
  - 任务报错定位&引导 `1期`
  <img width="1308" alt="image" src="https://github.com/TencentBlueKing/bk-job/assets/3852595/7753f006-d383-4433-8316-2ad23f1ef774">

  - 简单的文本处理 `1期`
  <img width="712" alt="image" src="https://github.com/TencentBlueKing/bk-job/assets/3852595/45e979a1-dacd-4df8-94b8-27d553ee60af">

  - 全局搜索 `2期`
  <img width="714" alt="image" src="https://github.com/TencentBlueKing/bk-job/assets/3852595/5a230aba-7d3b-4dda-8849-195e5c2cbff2">

  - 信息替换 `2期`
  <img width="713" alt="image" src="https://github.com/TencentBlueKing/bk-job/assets/3852595/d82a2939-c46f-4df4-915b-42960f2e5a83">

  - 任务联动执行 `2期`
  <img width="712" alt="image" src="https://github.com/TencentBlueKing/bk-job/assets/3852595/3fcc6b93-58b6-4d4d-9591-e0070972147f">

**Comment by jsonwan** [comment]
多文件场景下，报错信息取并集进行传递大模型的处理：

1. 只出现“源文件上传出错”时（下载的报错和源文件对应上），仅处理源文件上传的错误信息解析，并告知用户主因是源文件上传出错，出错的原因是xxxxx
2. 出现“源文件上传+不同文件下载出错”时，一并传给大模型处理（但是在第1点的基础上）
3. 源文件没错，“只有下载文件出错”时，仅传递下载文件条目的报错信息给大模型即可
4. 传递给大模型的信息只需要提取报错日志的“描述字段”即可，其他的进度、IP等等都不用，但是后端要记录对应关系，在JOB返回给用户的地方需要展示。

**Comment by jsonwan** [comment]
1. 源文件上传出错的case
回答用户时，要明确告知：源文件服务器[127.0.0.1,127.0.0.2] 上传文件[/tmp/abc.test] 失败原因：xxxxxxxxxx

2. 下载方出错的case
回答用户时，要明确告知：目标服务器[127.0.0.1] 下载文件[/tmp/20240702_test/打钩.png] 失败原因：xxxxxxxxxx

3. 上传和下载都出错的case
回答用户时，要明确告知：源文件服务器[127.0.0.1] 上传文件[/tmp/ddddd.test] 失败原因：xxxxxxxxxx；目标服务器[127.0.0.2] 下载文件[/tmp/20240702_test/打钩.png] 失败原因：xxxxxxxxxx
