### ISSUE TITLE
fix: 在其他业务下分发公共文件源的文件，选择文件时报无权限错误

### ISSUE THREAD

**Issue by jsonwan** [TencentBlueKing/bk-job#633]
**版本/分支/tag**
3.4.4.0
**问题描述**
在其他业务下分发公共文件源的文件，选择文件时报无权限错误
**如何复现**
在其他业务下分发公共文件源的文件，在IP选择器尝试选择文件
**预期结果**
对于公共文件源及在共享可见范围内的文件源，可正常选择文件分发不报错

**Comment by liuliaozhong** [comment]
在3.7.+版本上以下测试未复现
1. 业务集创建的文件源，共享到其他业务、业务集，被共享的业务、业务集文件源分发可以正常展示和选择文件，及作业成功执行。
2. 业务创建的文件源，共享到其他业务、业务集，结果同1
