### ISSUE TITLE
perf: 无权限提示信息带上用户名

### ISSUE THREAD

**Issue by jsonwan** [TencentBlueKing/bk-job#784]

**Comment by jsonwan** [comment]
![image](https://user-images.githubusercontent.com/53823124/162416676-05f2dff1-486f-4ffa-b5b4-19e9a314b081.png)

**Comment by jsonwan** [comment]
![企业微信截图_16494132277955](https://user-images.githubusercontent.com/53823124/162416825-d54ffdf4-f1d7-43ff-b54d-3b7a15dba08a.png)

**Comment by liuliaozhong** [comment]
该异常主要是用户在操作鉴权时，没有相应的操作权限，通过PermissionDeniedException对象抛出的异常，主要想到两种处理方式
### 方案1
PermissionDeniedException类中增加一个带有errorParams参数的构造方法，在需要抛出异常地方把username传进来。该异常用到的地方很多，所以改动很大，也不利于后续维护。
### 方案2
从服务请求来分析，来自三个方面，web调用、esb调用、服务内部调用，需要鉴权的是web调用和esb调用，这两类调用中都有统一的异常Advice处理类，可以在其处理统一权限异常逻辑中获取到username信息并添加到响应对象。
#### web调用
WebExceptionControllerAdvice#handlePermissionDeniedException()
添加一个buildAuthFailResp重载方法，username通过errorParams参数传给Response对象
`Response<T> buildAuthFailResp(AuthResultVO authResult, Object[] errorParams){{
new Response<>(errorCode, errorParams, null);
}`
#### esb调用
EsbExceptionControllerAdvice#handlePermissionDeniedException()
在AuthService接口中增加如下重载方法，增加errorParams参数
`<T> EsbResp<T> buildEsbAuthFailResp(List<PermissionActionResource> permissionActionResources, Object[] errorParams)`
在EsbResp类中增加如下重载方法，增加errorParams参数
`<T> EsbResp<T> buildAuthFailResult(EsbApplyPermissionDTO permission, Object[] errorParams){
EsbResp<T> esbResp = buildCommonFailResp(ErrorCode.BK_PERMISSION_DENIED, errorParams, null);
}`
#### i18n资源文件
对权限不足的错误码添加username通配符，如：
1238001=用户{0}权限不足
9900403=用户{0}权限不足

**Comment by jsonwan** [comment]
通过errorParams参数传递的话，还是需要在每个抛出异常的地方传进去，改动还是很大。
代码框架中有提取出web/esb请求的用户信息放到threadlocal数据中，一个请求只会有一个操作者，可以考虑直接从threadlocal数据中拿出用户身份使用，就不用每个地方都传一遍了

**Comment by liuliaozhong** [comment]
JobCommonInterceptor#addUsername(request)有把用户放到threadlocal中，每个web/esb请求都会执行到吗，能否直接拿出来用？

**Comment by liuliaozhong** [comment]
实现
![image](https://user-images.githubusercontent.com/120009833/209644137-3ed9f2ab-bd81-49a2-b176-1e5686c4a62d.png)

**Comment by jsonwan** [comment]
> JobCommonInterceptor#addUsername(request)有把用户放到threadlocal中，每个web/esb请求都会执行到吗，能否直接拿出来用？

设计上是都会执行到的，具体会不会可以分析下代码，也可以实践验证下
